export const GET_REMINDERS_RESPONSE = 'GET_REMINDERS_RESPONSE';
export const GET_REMINDER_RESPONSE = 'GET_REMINDER_RESPONSE';
export const ADD_NEW_REMINDER_RESPONSE = 'ADD_NEW_REMINDER_RESPONSE';
export const UPDATE_EXISTING_REMINDER_RESPONSE = 'UPDATE_EXISTING_REMINDER_RESPONSE';
export const DELETE_REMINDER_RESPONSE = 'DELETE_REMINDER_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
